mod.rs: Mark var as unused
error: unused variable: `guest_memory`

use vm_memory::{GuestMemoryAtomic, GuestMemoryMmap};

Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>