cpu.rs: Remove unused
error: unused imports: `GuestAddressSpace`, `GuestMemoryMmap`,
`GuestMemory`

Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>