memory_manager.rs: Unused snp_enabled flag
error: unused variable: `snp_enabled`

This involves also removing conditional compilation at various places.

Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>