performance_tests.rs: Use constant notation instead of cast
error: casting integer literal to `u64` is unnecessary

Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>